#!/usr/bin/env python

import rospy
import numpy as np

from geometry_msgs.msg import PoseStamped
from ackermann_msgs.msg import AckermannDriveStamped

if __name__ == "__main__":
    rospy.init_node("hallway_timer")
    start_pose = None
    start_time = None
    curr_pose = None
    goal_pose = None

    def pose_cb(pose_msg):
        curr_pose = np.array([pose_msg.pose.position.x, pose_msg.pose.position.y])
        if np.linalg.norm

    def ctrl_cb(ctrl_msg):
        if start_time is None:
            start_pose = curr_pose
            start_time = ctrl_msg.header.stamp.to_sec()

    pose_sub = rospy.Subscriber("/car/car_pose", PoseStamped, pose_cb)
    ctrl_sub = rospy.Subscriber("/car/mux/ackermann_cmd_mux/input/navigation", AckermannDriveStamped, ctrl_cb)
